apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-practice
  template:
    metadata:
      labels:
        app: devops-practice
    spec:
      containers:
      - name: app
        image: lalitgoel87/devops-practice:latest
        ports:
        - containerPort: 8080